spring.application.name=sghss

server.port=8080
server.servlet.context-path=/api

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SpringDoc OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.use-root-path=false
springdoc.api-docs.path=/v3/api-docs
springdoc.show-actuator=false
